# Generated by Django 5.0.6 on 2024-06-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufacture",
            new_name="Manufacturer",
        ),
    ]
